 const store= require('./appstore/store')
 const{ cakeActions}= require('./appstore/features/cakeSlice')
 console.log('initial state  ',store.getState())
 const unsub= store.subscribe(()=>{})
 store.dispatch(cakeActions.order())
 store.dispatch(cakeActions.order())
 store.dispatch(cakeActions.order())
 store.dispatch(cakeActions.restock(5))