 const store= require('./appstore/store')
//  const{ cakeActions}= require('./appstore/features/cakeSlice')
 const {fetchUsers}= require('./appstore/features/userSlice')
 const unsub=  store.subscribe(()=>{ console.log(store.getState())})
//  const unsub= store.subscribe(()=>{})
//  store.dispatch(cakeActions.order())
//  store.dispatch(cakeActions.order())
//  store.dispatch(cakeActions.order())
//  store.dispatch(cakeActions.restock(5))
store.dispatch(fetchUsers())
unsub()